import time 
import csv
globalPin=99976
globalPass='Python123$' 
globalNewPass='Concert997#'
col_head=['First Name',' Last Name','Mail','Age','Gender','Phone No.']
database_con='concert.csv' 

def shawn():
    global col_head 
    print()
    print("You have chosen Shawn Mendes Concert")
    print("Here are the details bout the concert")
    print()
    print("============================================================")
    print("        VENUE: Jakarta Convention Center       ")
    print("        DATE:  25-08-2020                       ")
    print("        TIME : 5:30pm  to 8:30 pm               ")
    print("============================================================")
    print()
    check=input("Would you like to continue (Yes/No): ")
    if(check=="Yes"):
        el=input("Enter you e-mail address: ")
        pas=input("Enter your password: ")
        if(pas==globalPass):
            print()
            print("Please wait....")
            time.sleep(3)
            print()
            print("Your e-mail address: ",el)
            print("Your password: ",pas)
            print("You will be sent an OPT no. please enter and continue")
            print()
            otp=2364
            time.sleep(2)
            print("     Your OTP no is: ",otp)
            print()
            ot=int(input("Enter OTP no: "))
            if(ot==2364):
                print()
                print("---------------------------------------")
                print()
                print("Please fill in the following details")
                global col_head
                global database_con 
                user_data=[] 
                print("...............GENERAL DETAILS...............")
                for field in col_head: 
                    print()
                    val=input(" Please Enter your" + " " + field + " : ") 
                    user_data.append(val)
                with open (database_con, "a") as f:
                    writer=csv.writer(f) 
                    writer.writerows([user_data]) 
                print()
                print("...............RECORDS SAVED SUCCESSFULLY...............")
                print() 
                time.sleep(2)
                print("We have 3 seating arrangement")
                print("1. VIP seat")
                print("2. A SEAT")
                print("3. B SEAT")
                print("You may chose the type of seat you want")
                c=int(input("Seat Type: "))
                if(c==1):
                     print()
                     print("You have chosen VIP seat")
                     print("The charge for one person is : 20,000,000")
                     n=int(input("Enter the no. of people: "))
                     if(n<=12): 
                         total=n*20000000
                         print()
                         print("Processing....") 
                         print() 
                         time.sleep(3)
                         print("Total Amount for your ticket: ",total)
                         print()
                         print("What payment medium would you like to choose to pay: ")
                         print("1.PAYPAL")
                         print("2.VISA")
                         pay=int(input("Please choose: "))
                         if(pay==1): 
                            print("You are going to pay through PAYPAL")
                            print()
                            print("Please enter few details")
                            fname=input("First Name: ")
                            print(fname)
                            print()
                            lname=input("Last Name: ")
                            print(lname)
                            print()
                            adde=input("Enter your street address1: ")
                            print(adde)
                            print()
                            city=input("Enter City: ")
                            print(city)
                            print()
                            pos=int(input("Enter Postal code: "))
                            print(pos)
                            print()
                            pin=int(input("Enter the pin code to pay: "))
                            if(pin==globalPin):
                                print()
                                print("Transaction in process...")
                                time.sleep(3)
                                print()
                                print(total,"has been withdrawn from your account")
                                print()
                                print("=========================================")
                                print("     Your tickets have been booked        ")
                                print("   Thank you for visiting our website     ")
                                print("=========================================")
                            else:
                                print("Sorry!! You pincode does not match")
                         elif(pay==2): 
                             print("You are going to pay through VISA")
                             print()
                             print("Please enter few details")
                             fname=input("First Name: ")
                             print(fname)
                             print()
                             lname=input("Last Name: ")
                             print(lname)
                             print()
                             adde=input("Enter your street address1: ")
                             print(adde)
                             print()
                             city=input("Enter City: ")
                             print(city)
                             print()
                             pos=int(input("Enter Postal code: "))
                             print(pos)
                             print()
                             pin=int(input("Enter the pin code to pay: "))
                             if(pin==globalPin):
                                 print()
                                 print("Transaction in process...")
                                 time.sleep(3)
                                 print()
                                 print(total,"has been withdrawn from your account")
                                 print()
                                 
                                 print("=========================================")
                                 print("     Your tickets have been booked        ")
                                 print("   Thank you for visiting our website     ")
                                 print("=========================================")
                             else:
                                 print("Sorry!! You pincode does not match") 
                         else:
                             print("Sorry!! You have to choose one of the medium to pay for your tickets")
                     else:
                         print("Sorry there are 12 seats available only. Please choose within the given choices")
                if(c==2):
                    print()
                    print("You have chosen A SEAT")
                    print("This comprised of 5 rows with 25 seats in each row")
                    print("Each person charge is: 15,000,000")
                    rowno=int(input("Enter your row no. of your choice: ")) 
                    n=int(input("Enter the no of seats to be booked: "))
                    if(n<=25):
                        total=n*15000000
                        print()
                        print("Processing....")
                        print()
                        time.sleep(3)
                        print("The row you have selected: ", rowno)
                        print("Total Amount for your ticket: ",total)
                        print()
                        print("What payment medium would you like to choose to pay: ")
                        print("1.PAYPAL")
                        print("2.VISA")
                        pay=int(input("Please choose: "))
                        if(pay==1):
                            print("You are going to pay through PAYPAL")
                            print()
                            print("Please enter few details")
                            fname=input("First Name: ")
                            print(fname)
                            print()
                            lname=input("Last Name: ")
                            print(lname)
                            print()
                            adde=input("Enter your street address1: ")
                            print(adde) 
                            print()
                            city=input("Enter City: ")
                            print(city)
                            print()
                            pos=int(input("Enter Postal code: "))
                            print(pos)
                            print()
                            pin=int(input("Enter the pin code to pay: "))
                            if(pin==globalPin):
                                print()
                                print("Transaction in process...")
                                time.sleep(3)
                                print()
                                print(total,"has been withdrawn from your account")
                                print()
                                print("=========================================")
                                print("     Your tickets have been booked        ")
                                print("   Thank you for visiting our website     ")
                                print("=========================================")
                            else:
                                print("Sorry!! You pincode does not match")
                        elif(pay==2):
                            print("You are going to pay through VISA")
                            print()
                            print("Please enter few details")
                            fname=input("First Name: ")
                            print(fname)
                            print()
                            lname=input("Last Name: ")
                            print(lname)
                            print()
                            adde=input("Enter your street address1: ")
                            print(adde)
                            print()
                            city=input("Enter City: ")
                            print(city)
                            print()
                            pos=int(input("Enter Postal code: "))
                            print(pos)
                            print()
                            pin=int(input("Enter the pin code to pay: "))
                            if(pin==globalPin):
                                print()
                                print("Transaction in process...")
                                time.sleep(3)
                                print()
                                print(total,"has been withdrawn from your account")
                                print()
                                print("=========================================")
                                print("     Your tickets have been booked        ")
                                print("   Thank you for visiting our website     ")
                                print("=========================================")
                            else:
                                print("Sorry!! You pincode does not match")
                        else:
                            print("Sorry!! You have to choose one of the medium to pay for your tickets")
                            print() 
                    else:
                        print("Sorry there are 25 seats available only. Please choose within the given choices")
                if(c==3):
                    print()
                    print("You have chosen B SEAT")
                    print("This comprised of 5 rows with 25 seats in each row")
                    print("Each person charge is: 10,000,000")
                    rowno=int(input("Enter your row no. of your choice: ")) 
                    n=int(input("Enter the no of seats to be booked: "))
                    if(n<=25):
                        total=n*10000000
                        print()
                        print("Processing....")
                        print()
                        time.sleep(3)
                        print("The row you have selected: ", rowno)
                        print("Total Amount for your ticket: ",total)
                        print()
                        print("What payment medium would you like to choose to pay: ")
                        print("1.PAYPAL")
                        print("2.VISA")
                        pay=int(input("Please choose: "))
                        if(pay==1):
                            print("You are going to pay through PAYPAL")
                            print()
                            print("Please enter few details")
                            fname=input("First Name: ")
                            print(fname)
                            print()
                            lname=input("Last Name: ")
                            print(lname)
                            print()
                            adde=input("Enter your street address1: ")
                            print(adde) 
                            print()
                            city=input("Enter City: ")
                            print(city)
                            print()
                            pos=int(input("Enter Postal code: "))
                            print(pos)
                            print()
                            pin=int(input("Enter the pin code to pay: "))
                            if(pin==globalPin):
                                print()
                                print("Transaction in process...")
                                time.sleep(3)
                                print()
                                print(total,"has been withdrawn from your account")
                                print()
                                print("=========================================")
                                print("     Your tickets have been booked        ")
                                print("   Thank you for visiting our website     ")
                                print("=========================================")
                            else:
                                print("Sorry!! You pincode does not match")
                        elif(pay==2):
                            print("You are going to pay through VISA")
                            print()
                            print("Please enter few details") 
                            fname=input("First Name: ")
                            print(fname)
                            print()
                            lname=input("Last Name: ")
                            print(lname)
                            print()
                            adde=input("Enter your street address1: ")
                            print(adde)
                            print()
                            city=input("Enter City: ")
                            print(city)
                            print()
                            pos=int(input("Enter Postal code: "))
                            print(pos)
                            print()
                            pin=int(input("Enter the pin code to pay: "))
                            if(pin==globalPin):
                                print()
                                print("Transaction in process...")
                                time.sleep(3)
                                print()
                                print(total,"has been withdrawn from your account")
                                print()
                                print("=========================================")
                                print("     Your tickets have been booked        ")
                                print("   Thank you for visiting our website     ")
                                print("=========================================")
                            else:
                                print("Sorry!! You pincode does not match")
                        else:
                            print("Sorry!! You have to choose one of the medium to pay for your tickets")
                            print() 
                    else:
                        print("Sorry there are 25 seats available only. Please choose within the given choices")
                
            else:
                print()
                print("Oops! OTP no. ENTERED WRONG Try Again")
                print() 
        else:
            print()
            print("PASSWORD entered WRONG! Please try again")
            print()
    else:
        print()
        
        print("------------------------------------------------------------------------------------------------------------")
        print("         THANK YOU FOR VISITING OUR WEBSITE                    ")
        print("------------------------------------------------------------------------------------------------------------")


def bts():
    print()
    print("You have chosen BTS Concert")
    print("Here are the details bout the concert")
    print()
    print("============================================================")
    print("        VENUE: Jakarta Convention Center       ")
    print("        DATE:  31-12-2020                                 ")
    print("        TIME : 5:30pm  to 8:30 pm                    ")
    print("============================================================")
    print()
    check=input("Would you like to continue (Yes/No): ")
    if(check=="Yes"):
        el=input("Enter you e-mail address: ")
        pas=input("Enter your password: ")
        if(pas==globalNewPass):
            print()
            print("Please wait....")
            time.sleep(3)
            print()
            print("Your e-mail address: ",el)
            print("Your password: ",pas)
            print("You will be sent an OPT please enter and continue")
            print()
            otp=2364
            time.sleep(2)
            print("     Your OTP no is: ",otp)
            print()
            ot=int(input("Enter OTP no: "))
            if(ot==2364):
                print()
                print("---------------------------------------")
                print("Please fill in the following details")
                global col_head
                global database_con 
                user_data=[] 
                print(".................GENERAL DETAILS.................")
                for field in col_head: 
                    print()
                    val=input(" Please Enter your" + " " + field + " : ") 
                    user_data.append(val)
                with open (database_con, "a") as f:
                    writer=csv.writer(f) 
                    writer.writerows([user_data]) 
                print()
                print("...............RECORDS SAVED SUCCESSFULLY...............")
                print()
                time.sleep(2)
                print("We have 3 seating arrangement")
                print("1.VIP seat")
                print("2. A SEAT")
                print("3. B SEAT")
                print("You may chose the type of seat you want")
                c=int(input("Seat Type: "))
                if(c==1):
                     print()
                     print("You have chosen VIP seat")
                     print("The charge for one person is : 20,000,000")
                     n=int(input("Enter the no. of people: "))
                     if(n<=12): 
                         total=n*20000000
                         print()
                         print("Processing....") 
                         print() 
                         time.sleep(3)
                         print("Total Amount for your ticket: ",total)
                         print()
                         print("What payment medium would you like to choose to pay: ")
                         print("1.PAYPAL")
                         print("2.VISA")
                         pay=int(input("Please choose: "))
                         if(pay==1): 
                            print("You are going to pay through PAYPAL")
                            print()
                            print("Please enter few details")
                            fname=input("First Name: ")
                            print(fname)
                            print()
                            lname=input("Last Name: ")
                            print(lname)
                            print()
                            adde=input("Enter your street address1: ")
                            print(adde)
                            print()
                            city=input("Enter City: ")
                            print(city)
                            print()
                            pos=int(input("Enter Postal code: "))
                            print(pos)
                            print()
                            pin=int(input("Enter the pin code to pay: "))
                            if(pin==globalPin):
                                print()
                                print("Transaction in process...")
                                time.sleep(3)
                                print()
                                print(total,"has been withdrawn from your account")
                                print()
                                print("=========================================")
                                print("     Your tickets have been booked        ")
                                print("   Thank you for visiting our website     ")
                                print("=========================================")
                            else:
                                print("Sorry!! You pincode does not match")
                         elif(pay==2): 
                             print("You are going to pay through VISA")
                             print()
                             print("Please enter few details")
                             fname=input("First Name: ")
                             print(fname)
                             print()
                             lname=input("Last Name: ")
                             print(lname)
                             print()
                             adde=input("Enter your street address1: ")
                             print(adde)
                             print()
                             city=input("Enter City: ")
                             print(city)
                             print()
                             pos=int(input("Enter Postal code: "))
                             print(pos)
                             print()
                             pin=int(input("Enter the pin code to pay: "))
                             if(pin==globalPin):
                                 print()
                                 print("Transaction in process...")
                                 time.sleep(3)
                                 print()
                                 print(total,"has been withdrawn from your account")
                                 print()
                                 print("=========================================")
                                 print("     Your tickets have been booked        ")
                                 print("   Thank you for visiting our website     ")
                                 print("=========================================")
                             else:
                                 print("Sorry!! You pincode does not match") 
                         else:
                             print("Sorry!! You have to choose one of the medium to pay for your tickets")
                     else:
                         print("Sorry there are 12 seats available only. Please choose within the given choices")
                if(c==2):
                    print()
                    print("You have chosen A SEAT")
                    print("This comprised of 5 rows with 25 seats in each row")
                    print("Each person charge is: 15,000,000")
                    rowno=int(input("Enter your row no. of your choice: ")) 
                    n=int(input("Enter the no of seats to be booked: "))
                    if(n<=25):
                        total=n*15000000
                        print()
                        print("Processing....")
                        print()
                        time.sleep(3)
                        print("The row you have selected: ", rowno)
                        print("Total Amount for your ticket: ",total)
                        print()
                        print("What payment medium would you like to choose to pay: ")
                        print("1.PAYPAL")
                        print("2.VISA")
                        pay=int(input("Please choose: "))
                        if(pay==1):
                            print("You are going to pay through PAYPAL")
                            print()
                            print("Please enter few details")
                            fname=input("First Name: ")
                            print(fname)
                            print()
                            lname=input("Last Name: ")
                            print(lname)
                            print()
                            adde=input("Enter your street address1: ")
                            print(adde) 
                            print()
                            city=input("Enter City: ")
                            print(city)
                            print()
                            pos=int(input("Enter Postal code: "))
                            print(pos)
                            print()
                            pin=int(input("Enter the pin code to pay: "))
                            if(pin==globalPin):
                                print()
                                print("Transaction in process...")
                                time.sleep(3)
                                print()
                                print(total,"has been withdrawn from your account")
                                print()
                                print("=========================================")
                                print("     Your tickets have been booked        ")
                                print("   Thank you for visiting our website     ")
                                print("=========================================")
                            else:
                                print("Sorry!! You pincode does not match")
                        elif(pay==2):
                            print("You are going to pay through VISA")
                            print()
                            print("Please enter few details")
                            fname=input("First Name: ")
                            print(fname)
                            print()
                            lname=input("Last Name: ")
                            print(lname)
                            print()
                            adde=input("Enter your street address1: ")
                            print(adde)
                            print()
                            city=input("Enter City: ")
                            print(city)
                            print()
                            pos=int(input("Enter Postal code: "))
                            print(pos)
                            print()
                            pin=int(input("Enter the pin code to pay: "))
                            if(pin==globalPin):
                                print()
                                print("Transaction in process...")
                                time.sleep(3)
                                print()
                                print(total,"has been withdrawn from your account")
                                print()
                                print("=========================================")
                                print("     Your tickets have been booked        ")
                                print("   Thank you for visiting our website     ")
                                print("=========================================")
                            else:
                                print("Sorry!! You pincode does not match")
                        else:
                            print("Sorry!! You have to choose one of the medium to pay for your tickets")
                            print() 
                    else:
                        print("Sorry there are 25 seats available only. Please choose within the given choices")
                if(c==3):
                    print()
                    print("You have chosen B SEAT")
                    print("This comprised of 5 rows with 25 seats in each row")
                    print("Each person charge is: 10,000,000")
                    rowno=int(input("Enter your row no. of your choice: ")) 
                    n=int(input("Enter the no of seats to be booked: "))
                    if(n<=25):
                        total=n*10000000
                        print()
                        print("Processing....")
                        print()
                        time.sleep(3)
                        print("The row you have selected: ", rowno)
                        print("Total Amount for your ticket: ",total)
                        print()
                        print("What payment medium would you like to choose to pay: ")
                        print("1.PAYPAL")
                        print("2.VISA")
                        pay=int(input("Please choose: "))
                        if(pay==1):
                            print("You are going to pay through PAYPAL")
                            print()
                            print("Please enter few details")
                            fname=input("First Name: ")
                            print(fname)
                            print()
                            lname=input("Last Name: ")
                            print(lname)
                            print()
                            adde=input("Enter your street address1: ")
                            print(adde) 
                            print()
                            city=input("Enter City: ")
                            print(city)
                            print()
                            pos=int(input("Enter Postal code: "))
                            print(pos)
                            print()
                            pin=int(input("Enter the pin code to pay: "))
                            if(pin==globalPin):
                                print()
                                print("Transaction in process...")
                                time.sleep(3)
                                print()
                                print(total,"has been withdrawn from your account")
                                print()
                                print("=========================================")
                                print("     Your tickets have been booked        ")
                                print("   Thank you for visiting our website     ")
                                print("=========================================")
                            else:
                                print("Sorry!! You pincode does not match")
                        elif(pay==2):
                            print("You are going to pay through VISA")
                            print()
                            print("Please enter few details")
                            fname=input("First Name: ")
                            print(fname)
                            print()
                            lname=input("Last Name: ")
                            print(lname)
                            print()
                            adde=input("Enter your street address1: ")
                            print(adde)
                            print()
                            city=input("Enter City: ")
                            print(city)
                            print()
                            pos=int(input("Enter Postal code: "))
                            print(pos)
                            print()
                            pin=int(input("Enter the pin code to pay: "))
                            if(pin==globalPin):
                                print()
                                print("Transaction in process...")
                                time.sleep(3)
                                print()
                                print(total,"has been withdrawn from your account")
                                print()
                                print("=========================================")
                                print("     Your tickets have been booked        ")
                                print("   Thank you for visiting our website     ")
                                print("=========================================")
                            else:
                                print("Sorry!! You pincode does not match")
                        else:
                            print("Sorry!! You have to choose one of the medium to pay for your tickets")
                            print() 
                    else:
                        print("Sorry there are 25 seats available only. Please choose within the given choices")
                
            else:
                print()
                print("Oops! OTP no. ENTERED WRONG Try Again")
                print()
        else:
            print()
            print("PASSWORD entered WRONG! Please try again")
            print()
    else:
        print()
        print("--------------------------------------------------------------------------------------------------------------------")
        print("         THANK YOU FOR VISITING OUR WEBSITE                          ")
        print("--------------------------------------------------------------------------------------------------------------------")
    

print("         *******************************************************            ")
print("                  WELCOME TO 'BOOK MY TICKET' WEBSITE                           ")
print("         ********************************************************           ")
print()
print()
time.sleep(2)
print("This year we will be witnessing 2 concerts taking place in August and Dec.")
print("2 World Wide famous artists will be performing in Jakarta")
print()
print("ARE YOU READYYYY!!!!!")
time.sleep(3)
print()
print("HERE WE GOOOO!!!") 
print()
print("------------------------------------------------------------------------------------------")
print()
print("# On 25th August SHAWN MENDES will be performing in Jakarta" )
print("...........................................................................")
print("        VENUE: Jakarta Convention Center       ")
print("        DATE:  25-08-2020                                 ")
print("        TIME : 5:30pm  to 8:30 pm                    ")
print("......................................................................... .") 
print()
print()
print()
time.sleep(3)
print("# On 31st BTS  will be performing in Jakarta" )
print("..........................................................................")
print("        VENUE: Jakarta Convention Center      ")
print("        DATE:  31-12-2020                                ")
print("        TIME : 5:30pm  to 8:30 pm                   ")
print("..........................................................................")
print()
print("Book tickets in advance to witness something mesmerizing and beautiful event" )
time.sleep(3)
while True:
        print()
        print()
        print()
        print()
        print("Please choose which concert would you like to go")
        print("********************************")
        print("1.SHAWN MENDES CONCERT")
        print("2.BTS CONCERT")
        print("3.Exit")
        print("********************************")
        choice=int(input("Please choose from 1 to 3: "))
        if(choice>=1 and choice<=2):
            if(choice==1):
                shawn()
            elif(choice==2):
                bts()
        else:
            print("-------------------------------------------------------------------------------------------------------------")
            print("         THANK YOU FOR VISITING OUR WEBSITE                    ")
            print("--------------------------------------------------------------------------------------------------------------")
            break  
